version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: public-pool_web_1
      APP_PORT: 80
  
  web:
    image: ghcr.io/sethforprivacy/public-pool-ui:latest
    restart: unless-stopped
    environment:
      - DOMAIN=$DEVICE_DOMAIN_NAME
