version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: public-pool_caddy_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  caddy:
    image: caddy:2.6.4-alpine@sha256:4dfec6c3b22c36b63ea4a3633c7cdbdaa9926d1324c27db2b0e2b70ef9cd105a
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/caddy-data/Caddyfile:/etc/caddy/Caddyfile

  web:
    image: smolgrrr/public-pool-ui:latest
    restart: unless-stopped
    stop_grace_period: 30s

  server:
    image: sethforprivacy/public-pool:4bb00f2@sha256:0fc82e7123be68650c9e31f57a5a206e622acbcaa170e31219a488818ad6da6b
    restart: unless-stopped
    stop_grace_period: 30s
    ports:
      - "0.0.0.0:3333:3333/tcp"
    volumes:
      - "${APP_DATA_DIR}/data/public-pool-db:/public-pool/DB"
    environment:
      - NODE_ENV=production
      - BITCOIN_RPC_URL=http://${APP_BITCOIN_NODE_IP}
      - BITCOIN_RPC_USER=${APP_BITCOIN_RPC_USER}
      - BITCOIN_RPC_PASSWORD=${APP_BITCOIN_RPC_PASS}
      - BITCOIN_RPC_PORT=${APP_BITCOIN_RPC_PORT}
      - BITCOIN_RPC_TIMEOUT=10000
      - BITCOIN_ZMQ_HOST="tcp://${APP_BITCOIN_NODE_IP}:${APP_BITCOIN_ZMQ_RAWBLOCK_PORT}"
      - API_PORT=3334
      - STRATUM_PORT=3333
      - NETWORK=mainnet
      - API_SECURE=false
      - ENABLE_SOLO=true
      - ENABLE_PROXY=false
