version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: synapse_server_1
      APP_PORT: $APP_SYNAPSE_PORT
      PROXY_AUTH_ADD: "false"
      
  server:
    image: matrixdotorg/synapse:latest
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      SYNAPSE_SERVER_NAME: "${APP_HIDDEN_SERVICE}"
      SYNAPSE_REPORT_STATS: "yes"
