version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: libreoffice_server_1
      APP_PORT: 3000

  server:
    image: linuxserver/libreoffice:7.5.5@sha256:b8791a12818f52b714f55643c0086252610513f3960fc139cc3b6da90f4bebe4
    restart: on-failure
    stop_grace_period: 1m
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config