version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: qbittorrent_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  server:
    image: hotio/qbittorrent:release-4.6.2@sha256:9fec00002f576ea20faea2934b4cce9e5aec06a64ffe46ba077bca5644be1b0a
    environment:
      - PUID=1000
      - PGID=1000
      # - UMASK=002
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${UMBREL_ROOT}/data/storage/downloads:/downloads
    restart: on-failure