version: '3.7'

services:
  app_proxy:
    environment:
      APP_HOST: planka_web_1
      APP_PORT: 1337

  web:
    image: ghcr.io/plankanban/planka:1.15.3@sha256:b943e3c3b20c23d6e7da299f067f172138586fe216b9e6a954e6634fb39d2fed
    command: >
      bash -c
        "for i in `seq 1 30`; do
          ./start.sh &&
          s=$$? && break || s=$$?;
          echo \"Tried $$i times. Waiting 5 seconds...\";
          sleep 5;
        done; (exit $$s)"
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/assets/user-avatars:/app/public/user-avatars
      - ${APP_DATA_DIR}/data/assets/project-background-images:/app/public/project-background-images
      - ${APP_DATA_DIR}/data/assets/attachments:/app/private/attachments
    environment:
      - BASE_URL=http://$DEVICE_DOMAIN_NAME:1337
      - TRUST_PROXY=0
      - DATABASE_URL=postgresql://postgres@postgres/planka
      - SECRET_KEY=$APP_PASSWORD
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=planka
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  user-avatars:
  project-background-images:
  attachments:
  db: