version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: overseerr_server_1
      APP_PORT: 5055
      PROXY_AUTH_WHITELIST: "/api/*"

  server:
    image: linuxserver/overseerr:1.33.2@sha256:4aaee70f051eaa8e789379a6549664492100e0a0a0cf6a0148b2036c4669d53a
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
    restart: on-failure