version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: robosats_web_1
      APP_PORT: 12596

  web:
    image: recksato/robosats-client:0.5.3-alpha@sha256:987994f561aa9606d87147844edafeb758fdd2c575c290a932f7f4033c4c53d4
    restart: on-failure
    stop_grace_period: 1m
    init: true
    environment:
      TOR_PROXY_IP: ${TOR_PROXY_IP}
      TOR_PROXY_PORT: ${TOR_PROXY_PORT}
