version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: homebox_web_1
      APP_PORT: 7745
    
  web:
    image: ghcr.io/hay-kot/homebox:v0.10.1@sha256:542f3d6156c7431b2127b35b37f97a121754dd92abb910afe1bbf0008706d2a1
    restart: on-failure
    user: 1000:1000
    environment:
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_UPLOAD_SIZE=10
    volumes:
      - ${APP_DATA_DIR}/data:/data/
