version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: uptime-kuma_server_1
      APP_PORT: 3001

  server:
    image: louislam/uptime-kuma:1.23.3@sha256:7d8b69a280bd9fa45d21c44a4f9b133b52925212c5d243f27ef03bcad33de2c1
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/uptime-kuma:/app/data
